stream_load_url = http://some_dors.com:8080/api/wushilin/example_table/_stream_load
# database is not required when stream_load_url is defined.
database = some_database
username = some_user
password = some_password
columns = event_time,user_id,event_name
# Supported modes: csv, json
mode = json
sender_batch_size = 1

# Optional tuning
doris_upload_timeout_ms = 300000
queue_timeout_ms = 50000
batch_bytes = 94371800
max_buffered_requests = 100
linger_ms = 200
doris_upload_request_timeout_ms = 300000
poll_timeout_ms = 3000000
report_interval_ms = 3000
threads = 5
sender_workers = 25
validation = syntax
# Supported wait modes: sync, callback, none
wait_mode = callback
debug = false
fake_send = true
fake_send_delay_ms = 10
data_repeats = 10000000

row = {NOW},{ROW_ID},login
row = {NOW},{ROW_ID},logout
